// todo-vue/src/components/TodoInput.vue
<template>
  <v-container>
    <v-row justify="center">
      <v-col md="2">
        <v-text-field label="Todo" v-model="todo" :value="todo"></v-text-field>
      </v-col>
      <v-col md="1">
        <v-btn class="ma-2" outlined color="primary" v-on:click="submit(todo)">
          Add todo
        </v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'TodoInput',
  props: { addTodo: Function },
  data() {
    return {
      todo: '',
    };
  },
  methods: {
    submit: function(text: string): void {
      if (text !== '') this.addTodo(text);
      this.todo = '';
    },
  },
});
</script>

// todo-react/src/components/TodoInput.tsx
import React from "react";
import { Grid, Button, TextField } from "@material-ui/core";

type Props = {
  addTodo(text: string): void;
};

type State = {
  text: string;
};

class TodoInput extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { text: "" };
  }

  submitTodo = () => {
    const { text } = this.state;
    if (text !== "") {
      this.props.addTodo(text);
      this.setState({ text: "" });
    }
  };

  render() {
    const { text } = this.state;
    return (
      <Grid
        container
        direction="row"
        justify="center"
        alignItems="center"
        spacing={8}
      >
        <Grid item>
          <TextField
            value={text}
            label="Todo"
            onChange={event => this.setState({ text: event.target.value })}
          />
        </Grid>
        <Grid item>
          <Button color="primary" variant="outlined" onClick={this.submitTodo}>
            Add todo
          </Button>
        </Grid>
      </Grid>
    );
  }
}

export default TodoInput;
