// todo-react/src/components/App.tsx
import React from "react";
import { Grid } from "@material-ui/core";
import Header from "./Header";
import TodoInput from "./TodoInput";
import Todo from "./Todo";
import TodoList from "./TodoList";

type Props = {};

type State = {
  todos: Todo[];
};

class App extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      todos: [
        { id: 0, text: "Faire les courses" },
        { id: 1, text: "Poster une  lettre de Noël" },
        { id: 2, text: "Acheter des cadeaux" }
      ]
    };
  }

  addTodo = (text: string) => {
    this.setState({
      todos: [...this.state.todos, { id: this.state.todos.length, text }]
    });
  };

  deleteTodo = (id: number) => {
    this.setState({
      todos: this.state.todos.filter(todo => todo.id !== id)
    });
  };

  render() {
    const { todos } = this.state;
    return (
      <>
        <Header />
        <Grid
          container
          direction="column"
          justify="center"
          alignItems="center"
          spacing={8}
          style={{ marginTop: 10 }}
        >
          <Grid item>
            <TodoInput addTodo={this.addTodo} />
          </Grid>
          <Grid item>
            <TodoList todos={todos} deleteTodo={this.deleteTodo} />
          </Grid>
        </Grid>
      </>
    );
  }
}

export default App;

// todo-vue/src/components/App.vue
<template>
  <v-app id="app">
    <Header />
    <v-container>
      <v-col justify="center">
        <TodoInput :addTodo="addTodo" />
        <TodoList :todos="todos" :deleteTodo="deleteTodo" />
      </v-col>
    </v-container>
  </v-app>
</template>

<script lang="ts">
import Vue from 'vue';
import Header from './Header.vue';
import TodoInput from './TodoInput.vue';
import TodoList from './TodoList.vue';
import Todo from './Todo';

export default Vue.extend({
  name: 'app',
  components: {
    Header,
    TodoInput,
    TodoList,
  },
  data() {
    return {
      todos: [
        { id: 0, text: 'Faire les courses' },
        { id: 1, text: 'Poster une  lettre de Noël' },
        { id: 2, text: 'Acheter des cadeaux' },
      ],
    };
  },
  methods: {
    addTodo: function(todo: string): void {
      this.todos.push({ id: this.todos.length, text: todo });
    },
    deleteTodo: function(id: number): void {
      this.todos = this.todos.filter(todo => todo.id !== id);
    },
  },
});
</script>

<style>
#app {
  padding: 6px;
}
</style>
