// todo-react/src/components/TodoList.tsx
import React from "react";
import Todo from "./Todo";
import TodoItem from "./TodoItem";
type Props = {
  todos: Todo[];
  deleteTodo(id: number): void;
};

class TodoList extends React.Component<Props> {
  render() {
    const { todos, deleteTodo } = this.props;
    return (
      <>
        {todos.map(todo => (
          <TodoItem key={todo.id} todo={todo} deleteTodo={deleteTodo} />
        ))}
      </>
    );
  }
}

export default TodoList;

// todo-vue/src/components/TodoList.vue
<template>
  <v-container>
    <TodoItem v-for="todo in todos" :deleteTodo="deleteTodo" :key="todo.id" v-bind:todo="todo" />
  </v-container>
</template>

<script lang="ts">
import Vue from 'vue';
import TodoItem from './TodoItem.vue';
import Todo from './Todo';

export default Vue.extend({
  name: 'TodoList',
  components: {
    TodoItem,
  },
  props: { todos: Array, deleteTodo: Function },
});
</script>
