// todo-react/src/components/TodoItem.tsx
import React from "react";
import { Grid, Button, Typography } from "@material-ui/core";
import Todo from "./Todo";

type Props = {
  todo: Todo;
  deleteTodo(id: number): void;
};

class TodoItem extends React.Component<Props> {
  render() {
    const { todo, deleteTodo } = this.props;
    return (
      <Grid
        container
        direction="row"
        justify="center"
        alignItems="center"
        spacing={8}
      >
        <Grid item>
          <Typography>{todo.text}</Typography>
        </Grid>
        <Grid item>
          <Button
            color="secondary"
            variant="outlined"
            onClick={() => deleteTodo(todo.id)}
          >
            Delete todo
          </Button>
        </Grid>
      </Grid>
    );
  }
}

export default TodoItem;

// todo-vue/src/components/TodoItem.vue
<template>
  <v-row justify="center">
    <v-col md="2">
      <p>{{todo.text}}</p>
    </v-col>
    <v-col md="1">
      <v-btn class="ma-2" outlined color="#F50057" v-on:click="deleteTodo(todo.id)">
        Delete todo
      </v-btn>
    </v-col>
  </v-row>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'TodoItem',
  props: { todo: Object, deleteTodo: Function },
});
</script>
