// todo-svelte/src/App.svelte
<script>
  import Header from "./Header.svelte";
  import TodoInput from "./TodoInput.svelte";
  import TodoItem from "./TodoItem.svelte";

  let todos = [
    { id: 0, text: "Faire les courses" },
    { id: 1, text: "Poster une  lettre de Noël" },
    { id: 2, text: "Acheter des cadeaux" }
  ];

  function addTodo(text) {
    todos = [...todos, { id: todos.length, text }];
  }

  function deleteTodo(id) {
    todos = todos.filter(todo => todo.id !== id);
  }
</script>

<Header />
<TodoInput {addTodo} />
<TodoItem {todos} {deleteTodo} />

// todo-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import Todo from "./Todo";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html"
})
export class AppComponent {
  title = "todo-angular";
  todos: Todo[];
  constructor() {
    this.todos = [
      { id: 0, text: "Faire les courses" },
      { id: 1, text: "Poster une  lettre de Noël" },
      { id: 2, text: "Acheter des cadeaux" }
    ];
  }

  addTodo(text: string): void {
    this.todos = [...this.todos, { id: this.todos.length, text }];
  }

  deleteTodo(id: number): void {
    this.todos = this.todos.filter(todo => todo.id !== id);
  }
}

<div>
  <app-header></app-header>
  <mat-grid-list cols="1" rowHeight="20:1">
    <mat-grid-tile
      ><app-todo-input (add)="addTodo($event)"></app-todo-input
    ></mat-grid-tile>
    <mat-grid-tile *ngFor="let todo of todos">
      <app-todo-item
        [todo]="todo"
        (delete)="deleteTodo($event)"
      ></app-todo-item>
    </mat-grid-tile>
  </mat-grid-list>
</div>
